
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public sealed partial class ABTestRateRange : Luban.BeanBase
{
    public ABTestRateRange(ByteBuf _buf) 
    {
        Rate = _buf.ReadFloat();
        Range = _buf.ReadFloat();
    }

    public static ABTestRateRange DeserializeABTestRateRange(ByteBuf _buf)
    {
        return new ABTestRateRange(_buf);
    }

    public readonly float Rate;
    public readonly float Range;
   
    public const int __ID__ = 1872170282;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Rate:" + Rate + ","
        + "Range:" + Range + ","
        + "}";
    }
}

}

