
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public sealed partial class Censorship : Luban.BeanBase
{
    public Censorship(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Text = _buf.ReadString();
    }

    public static Censorship DeserializeCensorship(ByteBuf _buf)
    {
        return new Censorship(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 屏蔽词
    /// </summary>
    public readonly string Text;
   
    public const int __ID__ = -1739814106;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Text:" + Text + ","
        + "}";
    }
}

}

