
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public sealed partial class ChannelABTestRateRange : Luban.BeanBase
{
    public ChannelABTestRateRange(ByteBuf _buf) 
    {
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AndroidDefault = new System.Collections.Generic.List<ABTestRateRange>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ABTestRateRange _e0;  _e0 = ABTestRateRange.DeserializeABTestRateRange(_buf); AndroidDefault.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AndroidMAI = new System.Collections.Generic.List<ABTestRateRange>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ABTestRateRange _e0;  _e0 = ABTestRateRange.DeserializeABTestRateRange(_buf); AndroidMAI.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AndroidAEO = new System.Collections.Generic.List<ABTestRateRange>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ABTestRateRange _e0;  _e0 = ABTestRateRange.DeserializeABTestRateRange(_buf); AndroidAEO.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AndroidVO = new System.Collections.Generic.List<ABTestRateRange>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ABTestRateRange _e0;  _e0 = ABTestRateRange.DeserializeABTestRateRange(_buf); AndroidVO.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);IOSDefault = new System.Collections.Generic.List<ABTestRateRange>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ABTestRateRange _e0;  _e0 = ABTestRateRange.DeserializeABTestRateRange(_buf); IOSDefault.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);IOSMAI = new System.Collections.Generic.List<ABTestRateRange>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ABTestRateRange _e0;  _e0 = ABTestRateRange.DeserializeABTestRateRange(_buf); IOSMAI.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);IOSAEO = new System.Collections.Generic.List<ABTestRateRange>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ABTestRateRange _e0;  _e0 = ABTestRateRange.DeserializeABTestRateRange(_buf); IOSAEO.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);IOSVO = new System.Collections.Generic.List<ABTestRateRange>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { ABTestRateRange _e0;  _e0 = ABTestRateRange.DeserializeABTestRateRange(_buf); IOSVO.Add(_e0);}}
    }

    public static ChannelABTestRateRange DeserializeChannelABTestRateRange(ByteBuf _buf)
    {
        return new ChannelABTestRateRange(_buf);
    }

    public readonly System.Collections.Generic.List<ABTestRateRange> AndroidDefault;
    public readonly System.Collections.Generic.List<ABTestRateRange> AndroidMAI;
    public readonly System.Collections.Generic.List<ABTestRateRange> AndroidAEO;
    public readonly System.Collections.Generic.List<ABTestRateRange> AndroidVO;
    public readonly System.Collections.Generic.List<ABTestRateRange> IOSDefault;
    public readonly System.Collections.Generic.List<ABTestRateRange> IOSMAI;
    public readonly System.Collections.Generic.List<ABTestRateRange> IOSAEO;
    public readonly System.Collections.Generic.List<ABTestRateRange> IOSVO;
   
    public const int __ID__ = 1501574631;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in AndroidDefault) { _e?.ResolveRef(tables); }
        foreach (var _e in AndroidMAI) { _e?.ResolveRef(tables); }
        foreach (var _e in AndroidAEO) { _e?.ResolveRef(tables); }
        foreach (var _e in AndroidVO) { _e?.ResolveRef(tables); }
        foreach (var _e in IOSDefault) { _e?.ResolveRef(tables); }
        foreach (var _e in IOSMAI) { _e?.ResolveRef(tables); }
        foreach (var _e in IOSAEO) { _e?.ResolveRef(tables); }
        foreach (var _e in IOSVO) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "AndroidDefault:" + Luban.StringUtil.CollectionToString(AndroidDefault) + ","
        + "AndroidMAI:" + Luban.StringUtil.CollectionToString(AndroidMAI) + ","
        + "AndroidAEO:" + Luban.StringUtil.CollectionToString(AndroidAEO) + ","
        + "AndroidVO:" + Luban.StringUtil.CollectionToString(AndroidVO) + ","
        + "iOSDefault:" + Luban.StringUtil.CollectionToString(IOSDefault) + ","
        + "iOSMAI:" + Luban.StringUtil.CollectionToString(IOSMAI) + ","
        + "iOSAEO:" + Luban.StringUtil.CollectionToString(IOSAEO) + ","
        + "iOSVO:" + Luban.StringUtil.CollectionToString(IOSVO) + ","
        + "}";
    }
}

}

