
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public sealed partial class ChannelConfigListInt : Luban.BeanBase
{
    public ChannelConfigListInt(ByteBuf _buf) 
    {
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AndroidDefault = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AndroidDefault.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AndroidMAI = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AndroidMAI.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AndroidAEO = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AndroidAEO.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AndroidVO = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AndroidVO.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);IOSDefault = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); IOSDefault.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);IOSMAI = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); IOSMAI.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);IOSAEO = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); IOSAEO.Add(_e0);}}
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);IOSVO = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); IOSVO.Add(_e0);}}
    }

    public static ChannelConfigListInt DeserializeChannelConfigListInt(ByteBuf _buf)
    {
        return new ChannelConfigListInt(_buf);
    }

    public readonly System.Collections.Generic.List<int> AndroidDefault;
    public readonly System.Collections.Generic.List<int> AndroidMAI;
    public readonly System.Collections.Generic.List<int> AndroidAEO;
    public readonly System.Collections.Generic.List<int> AndroidVO;
    public readonly System.Collections.Generic.List<int> IOSDefault;
    public readonly System.Collections.Generic.List<int> IOSMAI;
    public readonly System.Collections.Generic.List<int> IOSAEO;
    public readonly System.Collections.Generic.List<int> IOSVO;
   
    public const int __ID__ = 372960428;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "AndroidDefault:" + Luban.StringUtil.CollectionToString(AndroidDefault) + ","
        + "AndroidMAI:" + Luban.StringUtil.CollectionToString(AndroidMAI) + ","
        + "AndroidAEO:" + Luban.StringUtil.CollectionToString(AndroidAEO) + ","
        + "AndroidVO:" + Luban.StringUtil.CollectionToString(AndroidVO) + ","
        + "iOSDefault:" + Luban.StringUtil.CollectionToString(IOSDefault) + ","
        + "iOSMAI:" + Luban.StringUtil.CollectionToString(IOSMAI) + ","
        + "iOSAEO:" + Luban.StringUtil.CollectionToString(IOSAEO) + ","
        + "iOSVO:" + Luban.StringUtil.CollectionToString(IOSVO) + ","
        + "}";
    }
}

}

