
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public sealed partial class ChannelConfigFloat : Luban.BeanBase
{
    public ChannelConfigFloat(ByteBuf _buf) 
    {
        AndroidDefault = _buf.ReadFloat();
        AndroidMAI = _buf.ReadFloat();
        AndroidAEO = _buf.ReadFloat();
        AndroidVO = _buf.ReadFloat();
        IOSDefault = _buf.ReadFloat();
        IOSMAI = _buf.ReadFloat();
        IOSAEO = _buf.ReadFloat();
        IOSVO = _buf.ReadFloat();
    }

    public static ChannelConfigFloat DeserializeChannelConfigFloat(ByteBuf _buf)
    {
        return new ChannelConfigFloat(_buf);
    }

    public readonly float AndroidDefault;
    public readonly float AndroidMAI;
    public readonly float AndroidAEO;
    public readonly float AndroidVO;
    public readonly float IOSDefault;
    public readonly float IOSMAI;
    public readonly float IOSAEO;
    public readonly float IOSVO;
   
    public const int __ID__ = 348004183;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "AndroidDefault:" + AndroidDefault + ","
        + "AndroidMAI:" + AndroidMAI + ","
        + "AndroidAEO:" + AndroidAEO + ","
        + "AndroidVO:" + AndroidVO + ","
        + "iOSDefault:" + IOSDefault + ","
        + "iOSMAI:" + IOSMAI + ","
        + "iOSAEO:" + IOSAEO + ","
        + "iOSVO:" + IOSVO + ","
        + "}";
    }
}

}

