
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public sealed partial class ChannelConfigInt : Luban.BeanBase
{
    public ChannelConfigInt(ByteBuf _buf) 
    {
        AndroidDefault = _buf.ReadInt();
        AndroidMAI = _buf.ReadInt();
        AndroidAEO = _buf.ReadInt();
        AndroidVO = _buf.ReadInt();
        IOSDefault = _buf.ReadInt();
        IOSMAI = _buf.ReadInt();
        IOSAEO = _buf.ReadInt();
        IOSVO = _buf.ReadInt();
    }

    public static ChannelConfigInt DeserializeChannelConfigInt(ByteBuf _buf)
    {
        return new ChannelConfigInt(_buf);
    }

    public readonly int AndroidDefault;
    public readonly int AndroidMAI;
    public readonly int AndroidAEO;
    public readonly int AndroidVO;
    public readonly int IOSDefault;
    public readonly int IOSMAI;
    public readonly int IOSAEO;
    public readonly int IOSVO;
   
    public const int __ID__ = -21981270;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "AndroidDefault:" + AndroidDefault + ","
        + "AndroidMAI:" + AndroidMAI + ","
        + "AndroidAEO:" + AndroidAEO + ","
        + "AndroidVO:" + AndroidVO + ","
        + "iOSDefault:" + IOSDefault + ","
        + "iOSMAI:" + IOSMAI + ","
        + "iOSAEO:" + IOSAEO + ","
        + "iOSVO:" + IOSVO + ","
        + "}";
    }
}

}

