
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public sealed partial class Coordinate : Luban.BeanBase
{
    public Coordinate(ByteBuf _buf) 
    {
        X = _buf.ReadInt();
        Y = _buf.ReadInt();
    }

    public static Coordinate DeserializeCoordinate(ByteBuf _buf)
    {
        return new Coordinate(_buf);
    }

    public readonly int X;
    public readonly int Y;
   
    public const int __ID__ = -2102570600;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "X:" + X + ","
        + "Y:" + Y + ","
        + "}";
    }
}

}

