
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config
{ 
    [System.Flags]
    public enum EGoldenTouchRotate
    {
        Degree0 = 1,
        Degree90 = 2,
        Degree180 = 4,
        Degree270 = 8,
    }

} 

