
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public sealed partial class ExchangeConfig : Luban.BeanBase
{
    public ExchangeConfig(ByteBuf _buf) 
    {
        InCount = _buf.ReadInt();
        OutCount = _buf.ReadInt();
    }

    public static ExchangeConfig DeserializeExchangeConfig(ByteBuf _buf)
    {
        return new ExchangeConfig(_buf);
    }

    public readonly int InCount;
    public readonly int OutCount;
   
    public const int __ID__ = -1927519387;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "InCount:" + InCount + ","
        + "OutCount:" + OutCount + ","
        + "}";
    }
}

}

