
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public sealed partial class FloatRange : Luban.BeanBase
{
    public FloatRange(ByteBuf _buf) 
    {
        Min = _buf.ReadFloat();
        Max = _buf.ReadFloat();
    }

    public static FloatRange DeserializeFloatRange(ByteBuf _buf)
    {
        return new FloatRange(_buf);
    }

    public readonly float Min;
    public readonly float Max;
   
    public const int __ID__ = 964041825;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Min:" + Min + ","
        + "Max:" + Max + ","
        + "}";
    }
}

}

