
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public sealed partial class GoldenTouchItemIds : Luban.BeanBase
{
    public GoldenTouchItemIds(ByteBuf _buf) 
    {
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Ids = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Ids.Add(_e0);}}
    }

    public static GoldenTouchItemIds DeserializeGoldenTouchItemIds(ByteBuf _buf)
    {
        return new GoldenTouchItemIds(_buf);
    }

    public readonly System.Collections.Generic.List<int> Ids;
   
    public const int __ID__ = -2139485649;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Ids:" + Luban.StringUtil.CollectionToString(Ids) + ","
        + "}";
    }
}

}

