
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public sealed partial class GoldenTouchItemOccupancies : Luban.BeanBase
{
    public GoldenTouchItemOccupancies(ByteBuf _buf) 
    {
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Data = new System.Collections.Generic.List<GoldenTouchItemOccupancy>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { GoldenTouchItemOccupancy _e0;  _e0 = GoldenTouchItemOccupancy.DeserializeGoldenTouchItemOccupancy(_buf); Data.Add(_e0);}}
    }

    public static GoldenTouchItemOccupancies DeserializeGoldenTouchItemOccupancies(ByteBuf _buf)
    {
        return new GoldenTouchItemOccupancies(_buf);
    }

    public readonly System.Collections.Generic.List<GoldenTouchItemOccupancy> Data;
   
    public const int __ID__ = -627937758;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Data) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Data:" + Luban.StringUtil.CollectionToString(Data) + ","
        + "}";
    }
}

}

