
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public sealed partial class GoldenTouchItemOccupancy : Luban.BeanBase
{
    public GoldenTouchItemOccupancy(ByteBuf _buf) 
    {
        Coordinate = Coordinate.DeserializeCoordinate(_buf);
        GoldenTouchRotate = (EGoldenTouchRotate)_buf.ReadInt();
    }

    public static GoldenTouchItemOccupancy DeserializeGoldenTouchItemOccupancy(ByteBuf _buf)
    {
        return new GoldenTouchItemOccupancy(_buf);
    }

    public readonly Coordinate Coordinate;
    public readonly EGoldenTouchRotate GoldenTouchRotate;
   
    public const int __ID__ = 48508548;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Coordinate?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "Coordinate:" + Coordinate + ","
        + "GoldenTouchRotate:" + GoldenTouchRotate + ","
        + "}";
    }
}

}

