
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public sealed partial class IntRange : Luban.BeanBase
{
    public IntRange(ByteBuf _buf) 
    {
        Min = _buf.ReadInt();
        Max = _buf.ReadInt();
    }

    public static IntRange DeserializeIntRange(ByteBuf _buf)
    {
        return new IntRange(_buf);
    }

    public readonly int Min;
    public readonly int Max;
   
    public const int __ID__ = 617001646;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Min:" + Min + ","
        + "Max:" + Max + ","
        + "}";
    }
}

}

