
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public sealed partial class ItemConfig : Luban.BeanBase
{
    public ItemConfig(ByteBuf _buf) 
    {
        ItemId = _buf.ReadInt();
        ItemCount = _buf.ReadInt();
    }

    public static ItemConfig DeserializeItemConfig(ByteBuf _buf)
    {
        return new ItemConfig(_buf);
    }

    public readonly int ItemId;
    public readonly int ItemCount;
   
    public const int __ID__ = -764023723;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ItemId:" + ItemId + ","
        + "ItemCount:" + ItemCount + ","
        + "}";
    }
}

}

