
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public sealed partial class Language : Luban.BeanBase
{
    public Language(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Key = _buf.ReadString();
        CN = _buf.ReadString();
        EN = _buf.ReadString();
        ES = _buf.ReadString();
        RU = _buf.ReadString();
        JP = _buf.ReadString();
        KR = _buf.ReadString();
        FR = _buf.ReadString();
        DE = _buf.ReadString();
        PT = _buf.ReadString();
        IT = _buf.ReadString();
        TC = _buf.ReadString();
    }

    public static Language DeserializeLanguage(ByteBuf _buf)
    {
        return new Language(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Key
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// CN
    /// </summary>
    public readonly string CN;
    /// <summary>
    /// EN
    /// </summary>
    public readonly string EN;
    /// <summary>
    /// ES
    /// </summary>
    public readonly string ES;
    /// <summary>
    /// RU
    /// </summary>
    public readonly string RU;
    /// <summary>
    /// JP
    /// </summary>
    public readonly string JP;
    /// <summary>
    /// KR
    /// </summary>
    public readonly string KR;
    /// <summary>
    /// FR
    /// </summary>
    public readonly string FR;
    public readonly string DE;
    public readonly string PT;
    public readonly string IT;
    /// <summary>
    /// TC
    /// </summary>
    public readonly string TC;
   
    public const int __ID__ = -1548945544;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Key:" + Key + ","
        + "CN:" + CN + ","
        + "EN:" + EN + ","
        + "ES:" + ES + ","
        + "RU:" + RU + ","
        + "JP:" + JP + ","
        + "KR:" + KR + ","
        + "FR:" + FR + ","
        + "DE:" + DE + ","
        + "PT:" + PT + ","
        + "IT:" + IT + ","
        + "TC:" + TC + ","
        + "}";
    }
}

}

