
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public sealed partial class ParamConfig : Luban.BeanBase
{
    public ParamConfig(ByteBuf _buf) 
    {
        ParamName = _buf.ReadString();
        ParamFieldName = _buf.ReadString();
        ParamType = _buf.ReadString();
    }

    public static ParamConfig DeserializeParamConfig(ByteBuf _buf)
    {
        return new ParamConfig(_buf);
    }

    public readonly string ParamName;
    public readonly string ParamFieldName;
    public readonly string ParamType;
   
    public const int __ID__ = 2026033679;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ParamName:" + ParamName + ","
        + "ParamFieldName:" + ParamFieldName + ","
        + "ParamType:" + ParamType + ","
        + "}";
    }
}

}

