
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public sealed partial class ShopItems : Luban.BeanBase
{
    public ShopItems(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ShopItemName = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);DropGroupId = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); DropGroupId.Add(_e0);}}
        ShopItemType = _buf.ReadInt();
        RepeatPurchase = _buf.ReadBool();
        DefaultPrice = _buf.ReadString();
        IOSDefaultPrice = _buf.ReadString();
        RubPrice = _buf.ReadString();
        ProductId = _buf.ReadString();
    }

    public static ShopItems DeserializeShopItems(ByteBuf _buf)
    {
        return new ShopItems(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 商品名称
    /// </summary>
    public readonly string ShopItemName;
    /// <summary>
    /// 掉落组Id
    /// </summary>
    public readonly System.Collections.Generic.List<int> DropGroupId;
    /// <summary>
    /// 类别
    /// </summary>
    public readonly int ShopItemType;
    /// <summary>
    /// 是否可以重复购买
    /// </summary>
    public readonly bool RepeatPurchase;
    /// <summary>
    /// 默认价格
    /// </summary>
    public readonly string DefaultPrice;
    /// <summary>
    /// 默认价格
    /// </summary>
    public readonly string IOSDefaultPrice;
    /// <summary>
    /// 默认卢布价格
    /// </summary>
    public readonly string RubPrice;
    /// <summary>
    /// 计费点Id
    /// </summary>
    public readonly string ProductId;
   
    public const int __ID__ = -120084918;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ShopItemName:" + ShopItemName + ","
        + "DropGroupId:" + Luban.StringUtil.CollectionToString(DropGroupId) + ","
        + "ShopItemType:" + ShopItemType + ","
        + "RepeatPurchase:" + RepeatPurchase + ","
        + "DefaultPrice:" + DefaultPrice + ","
        + "IOSDefaultPrice:" + IOSDefaultPrice + ","
        + "RubPrice:" + RubPrice + ","
        + "ProductId:" + ProductId + ","
        + "}";
    }
}

}

