
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Game.Config
{
public partial class Tables
{
    public TbItem TbItem {get; }
    public TbLanguage TbLanguage {get; }
    public TbShopItems TbShopItems {get; }
    public TbCensorship TbCensorship {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbItem = new TbItem(loader("tbitem"));
        TbLanguage = new TbLanguage(loader("tblanguage"));
        TbShopItems = new TbShopItems(loader("tbshopitems"));
        TbCensorship = new TbCensorship(loader("tbcensorship"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbLanguage.ResolveRef(this);
        TbShopItems.ResolveRef(this);
        TbCensorship.ResolveRef(this);
    }
}

}
