
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public partial class TbCensorship
{
    private readonly System.Collections.Generic.Dictionary<int, Censorship> _dataMap;
    private readonly System.Collections.Generic.List<Censorship> _dataList;
    
    public TbCensorship(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Censorship>();
        _dataList = new System.Collections.Generic.List<Censorship>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Censorship _v;
            _v = Censorship.DeserializeCensorship(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Censorship> DataMap => _dataMap;
    public System.Collections.Generic.List<Censorship> DataList => _dataList;

    public Censorship GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Censorship Get(int key) => _dataMap[key];
    public Censorship this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

