
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public partial class TbShopItems
{
    private readonly System.Collections.Generic.Dictionary<int, ShopItems> _dataMap;
    private readonly System.Collections.Generic.List<ShopItems> _dataList;
    
    public TbShopItems(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ShopItems>();
        _dataList = new System.Collections.Generic.List<ShopItems>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ShopItems _v;
            _v = ShopItems.DeserializeShopItems(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ShopItems> DataMap => _dataMap;
    public System.Collections.Generic.List<ShopItems> DataList => _dataList;

    public ShopItems GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ShopItems Get(int key) => _dataMap[key];
    public ShopItems this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

