
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public sealed partial class ValueWithWeight : Luban.BeanBase
{
    public ValueWithWeight(ByteBuf _buf) 
    {
        Value = _buf.ReadInt();
        Weight = _buf.ReadInt();
    }

    public static ValueWithWeight DeserializeValueWithWeight(ByteBuf _buf)
    {
        return new ValueWithWeight(_buf);
    }

    public readonly int Value;
    public readonly int Weight;
   
    public const int __ID__ = -1522630897;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Value:" + Value + ","
        + "Weight:" + Weight + ","
        + "}";
    }
}

}

